version: "3.8"
services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db-init-scripts/create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser
      - POSTGRES_DB=test